version: '3.7'

services:

  react_acl:
    stdin_open: true
    container_name: react_acl
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1